### ISSUE TITLE
Goofed up code comment

### ISSUE THREAD

**Issue by wesruv** [backdrop-contrib/project_browser_server#5]
https://github.com/backdrop-contrib/project_browser_server/blob/1.x/project_browser_server.module#L21

**Comment by wesruv** [comment]
It's a dumb one, I know, but I thought since I noticed it, I would report it :stuck_out_tongue:

**Comment by quicksketch** [comment]
Thanks @wesruv, tidied this up in https://github.com/backdrop-contrib/project_browser_server/commit/31d7e000db80fb69f3204a186d7ebcb240f766a5.
